
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 15 06:34:46 GMT-05:00 2024
//----------------------------------------------------

package proyectofinal;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Class = 13;
  public static final int NumeroEntero = 54;
  public static final int Coma = 52;
  public static final int PuntoComa = 50;
  public static final int Finally = 35;
  public static final int Double = 30;
  public static final int Null = 38;
  public static final int If = 2;
  public static final int Void = 17;
  public static final int CorcheteAbierto = 48;
  public static final int Byte = 28;
  public static final int Static = 22;
  public static final int Super = 37;
  public static final int Default = 6;
  public static final int Interface = 14;
  public static final int ParentesisAbierto = 44;
  public static final int Else = 3;
  public static final int Extends = 15;
  public static final int Break = 10;
  public static final int Override = 66;
  public static final int Long = 26;
  public static final int Punto = 51;
  public static final int Return = 12;
  public static final int While = 7;
  public static final int NumeroDecimal = 55;
  public static final int Int = 24;
  public static final int Out = 59;
  public static final int LlaveCerrada = 47;
  public static final int Float = 29;
  public static final int For = 9;
  public static final int EOF = 0;
  public static final int DosPuntos = 65;
  public static final int OpIncremento = 42;
  public static final int error = 1;
  public static final int Switch = 4;
  public static final int Integer = 25;
  public static final int Implements = 16;
  public static final int Private = 20;
  public static final int Char = 32;
  public static final int Println = 60;
  public static final int Print = 61;
  public static final int OpAritmetico = 41;
  public static final int Do = 8;
  public static final int Catch = 34;
  public static final int Args = 63;
  public static final int Continue = 11;
  public static final int Case = 5;
  public static final int Public = 19;
  public static final int Protected = 21;
  public static final int Short = 27;
  public static final int String = 62;
  public static final int New = 18;
  public static final int CorcheteCerrado = 49;
  public static final int OpAsignacion = 43;
  public static final int CadenaTexto = 56;
  public static final int Identificador = 53;
  public static final int Try = 33;
  public static final int LlaveAbierta = 46;
  public static final int ParentesisCerrado = 45;
  public static final int OpComparacion = 40;
  public static final int Length = 64;
  public static final int Boolean = 31;
  public static final int Main = 57;
  public static final int OpLogico = 39;
  public static final int This = 36;
  public static final int Abstract = 23;
  public static final int SystemClass = 58;
}

